apiVersion: v1
kind: Service
metadata:
  name: tale-tinkerer-service
spec:
  selector:
    app: tale-tinkerer
  ports:
    - protocol: "TCP"
      port: 5001
      targetPort: 5001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tale-tinkerer
spec:
  selector:
    matchLabels:
      app: tale-tinkerer
  replicas: 5
  template:
    metadata:
      labels:
        app: tale-tinkerer
    spec:
      containers:
        - name: tale-tinkerer
          image: docker.io/rudrakshkarpe/taletinkerer:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
