apiVersion: v1
kind: Service
metadata:
  name: tale-tinkerer
  labels:
    run: tale-tinkerer
  namespace: gen-ai  
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: tale-tinkerer